import { Subject, Game, Badge } from '../types';

export const INITIAL_SUBJECTS: Subject[] = [
  // CÔNG NGHỆ 6, 7, 8, 9
  {
    id: 'sub_tech_6',
    code: 'CONG_NGHE_6',
    name: 'Công nghệ 6',
    gradeLevel: 6,
    schoolLevel: 'secondary',
    icon: 'Cpu',
    colorTheme: 'emerald',
    description: 'Nhà ở, bảo quản chế biến thực phẩm, trang phục và đồ dùng điện gia đình.',
  },
  {
    id: 'sub_tech_7',
    code: 'CONG_NGHE_7',
    name: 'Công nghệ 7',
    gradeLevel: 7,
    schoolLevel: 'secondary',
    icon: 'Sprout',
    colorTheme: 'emerald',
    description: 'Trồng trọt, bảo vệ cây trồng, kĩ thuật chăn nuôi và nuôi trồng thủy sản.',
  },
  {
    id: 'sub_tech_8',
    code: 'CONG_NGHE_8',
    name: 'Công nghệ 8',
    gradeLevel: 8,
    schoolLevel: 'secondary',
    icon: 'Wrench',
    colorTheme: 'emerald',
    description: 'Bản vẽ kĩ thuật, cơ khí chế tạo, kĩ thuật điện và an toàn điện trong nhà.',
  },
  {
    id: 'sub_tech_9',
    code: 'CONG_NGHE_9',
    name: 'Công nghệ 9',
    gradeLevel: 9,
    schoolLevel: 'secondary',
    icon: 'Cog',
    colorTheme: 'emerald',
    description: 'Lắp đặt mạng điện trong nhà, trồng cây ăn quả và định hướng nghề kĩ thuật.',
  },

  // HOẠT ĐỘNG TRẢI NGHIỆM, HƯỚNG NGHIỆP 6, 7, 8, 9
  {
    id: 'sub_hdtn_6',
    code: 'HDTN_HN_6',
    name: 'Hoạt động trải nghiệm, hướng nghiệp 6',
    gradeLevel: 6,
    schoolLevel: 'secondary',
    icon: 'Compass',
    colorTheme: 'amber',
    description: 'Khám phá bản thân, rèn luyện nền nếp và xây dựng tình bạn học đường thân thiện.',
  },
  {
    id: 'sub_hdtn_7',
    code: 'HDTN_HN_7',
    name: 'Hoạt động trải nghiệm, hướng nghiệp 7',
    gradeLevel: 7,
    schoolLevel: 'secondary',
    icon: 'Users',
    colorTheme: 'amber',
    description: 'Phát triển các mối quan hệ, quản lý cảm xúc và tham gia hoạt động thiện nguyện xã hội.',
  },
  {
    id: 'sub_hdtn_8',
    code: 'HDTN_HN_8',
    name: 'Hoạt động trải nghiệm, hướng nghiệp 8',
    gradeLevel: 8,
    schoolLevel: 'secondary',
    icon: 'Target',
    colorTheme: 'amber',
    description: 'Xây dựng hình ảnh bản thân, quản lý tài chính cá nhân và phòng chống xung đột.',
  },
  {
    id: 'sub_hdtn_9',
    code: 'HDTN_HN_9',
    name: 'Hoạt động trải nghiệm, hướng nghiệp 9',
    gradeLevel: 9,
    schoolLevel: 'secondary',
    icon: 'Briefcase',
    colorTheme: 'amber',
    description: 'Tìm hiểu thế giới nghề nghiệp trong thời đại 4.0, định hướng chọn trường và tương lai.',
  },

  // TIN HỌC 6, 7, 8, 9
  {
    id: 'sub_it_6',
    code: 'TIN_HOC_6',
    name: 'Tin học 6',
    gradeLevel: 6,
    schoolLevel: 'secondary',
    icon: 'Monitor',
    colorTheme: 'cyan',
    description: 'Thông tin và dữ liệu, mạng máy tính và Internet, sơ đồ tư duy Mindmap.',
  },
  {
    id: 'sub_it_7',
    code: 'TIN_HOC_7',
    name: 'Tin học 7',
    gradeLevel: 7,
    schoolLevel: 'secondary',
    icon: 'Table',
    colorTheme: 'cyan',
    description: 'Bảng tính điện tử Excel, phần mềm ứng dụng, đạo đức và văn hóa ứng xử mạng.',
  },
  {
    id: 'sub_it_8',
    code: 'TIN_HOC_8',
    name: 'Tin học 8',
    gradeLevel: 8,
    schoolLevel: 'secondary',
    icon: 'Code',
    colorTheme: 'cyan',
    description: 'Thuật toán logic, lập trình trực quan Scratch/Python, giải quyết vấn đề số.',
  },
  {
    id: 'sub_it_9',
    code: 'TIN_HOC_9',
    name: 'Tin học 9',
    gradeLevel: 9,
    schoolLevel: 'secondary',
    icon: 'Database',
    colorTheme: 'cyan',
    description: 'Cơ sở dữ liệu, mạng đa phương tiện, an toàn an ninh mạng và nghề tin học.',
  },

  // Môn Tiểu học mở rộng
  {
    id: 'sub_pri_tech',
    code: 'TIN_CONG_NGHE_TIEU_HOC',
    name: 'Tin học & Công nghệ Tiểu học',
    gradeLevel: 4,
    schoolLevel: 'primary',
    icon: 'Gamepad2',
    colorTheme: 'primarySchool-accent',
    description: 'Làm quen máy tính, nhận biết linh kiện và các thao tác thủ công sáng tạo.',
  },

  // Môn THPT mở rộng
  {
    id: 'sub_high_it',
    code: 'TIN_HOC_10',
    name: 'Tin học 10 (Khoa học Máy tính & Tin học ứng dụng)',
    gradeLevel: 10,
    schoolLevel: 'high',
    icon: 'Terminal',
    colorTheme: 'highSchool-indigo',
    description: 'Khoa học dữ liệu, lập trình Python nâng cao, kiến trúc máy tính và trí tuệ nhân tạo.',
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'badge_first_win',
    name: 'Khởi Đầu Nan',
    description: 'Hoàn thành ván chơi đầu tiên với điểm số xuất sắc',
    icon: 'Trophy',
    category: 'achievement',
    requiredXp: 50,
    requiredStreak: 0,
  },
  {
    id: 'badge_combo_king',
    name: 'Chiến Thần Tốc Độ',
    description: 'Đạt chuỗi Combo 5 câu trả lời đúng liên tiếp',
    icon: 'Zap',
    category: 'skill',
    requiredXp: 200,
    requiredStreak: 0,
  },
  {
    id: 'badge_scholar',
    name: 'Nhà Thông Thái',
    description: 'Tích lũy đạt 500 XP kiến thức trên hệ thống',
    icon: 'GraduationCap',
    category: 'milestone',
    requiredXp: 500,
    requiredStreak: 0,
  },
  {
    id: 'badge_master',
    name: 'Bậc Thầy Đuổi Hình',
    description: 'Tích lũy đạt 1,500 XP kiến thức đỉnh cao',
    icon: 'Crown',
    category: 'milestone',
    requiredXp: 1500,
    requiredStreak: 0,
  },
  {
    id: 'badge_streak_master',
    name: 'Chiến Binh Bền Bỉ',
    description: 'Duy trì chuỗi đăng nhập học tập 3 ngày liên tục',
    icon: 'Flame',
    category: 'loyalty',
    requiredXp: 300,
    requiredStreak: 3,
  },
];

export const INITIAL_GAMES: Game[] = [
  // GAME 1: TIN HỌC 6 - KHÁM PHÁ THẾ GIỚI MẠNG & DỮ LIỆU
  {
    id: 'game_it_6_catchword',
    title: 'Đuổi Hình Bắt Chữ: Thế Giới Mạng & Dữ Liệu',
    description: 'Thử thách nhìn hình đoán các khái niệm cốt lõi trong môn Tin học 6: Mạng máy tính, Sơ đồ tư duy, Dữ liệu số.',
    subjectId: 'sub_it_6',
    subjectName: 'Tin học 6',
    subjectCode: 'TIN_HOC_6',
    gameType: 'catch_word',
    schoolLevel: 'secondary',
    gradeLevel: 6,
    thumbnailUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=80',
    totalQuestions: 4,
    playsCount: 142,
    isPublished: true,
    questions: [
      {
        id: 'q_it6_1',
        gameId: 'game_it_6_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
        answerText: 'MẠNG MÁY TÍNH',
        hintText: 'Hệ thống kết nối nhiều thiết bị điện tử để chia sẻ dữ liệu và tài nguyên với nhau.',
        explanation: 'Mạng máy tính (Computer Network) là tập hợp các máy tính được kết nối theo một phương thức nào đó nhằm mục đích chia sẻ tài nguyên và trao đổi thông tin.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 1,
      },
      {
        id: 'q_it6_2',
        gameId: 'game_it_6_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
        answerText: 'SƠ ĐỒ TƯ DUY',
        hintText: 'Công cụ đồ họa thể hiện các ý tưởng phân nhánh xuất phát từ một chủ đề trung tâm.',
        explanation: 'Sơ đồ tư duy (Mindmap) giúp học sinh tổ chức, phân tích, tóm tắt và ghi nhớ kiến thức một cách trực quan, khoa học theo GDPT 2018.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 2,
      },
      {
        id: 'q_it6_3',
        gameId: 'game_it_6_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
        answerText: 'BẢO MẬT THÔNG TIN',
        hintText: 'Hành động đặt mật khẩu mạnh, chống mã độc để bảo vệ an toàn cho dữ liệu cá nhân.',
        explanation: 'Bảo mật thông tin là việc ngăn chặn sự truy cập, sử dụng, tiết lộ, gián đoạn trái phép đối với thông tin và dữ liệu số.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 3,
      },
      {
        id: 'q_it6_4',
        gameId: 'game_it_6_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        answerText: 'TRÌNH DUYỆT WEB',
        hintText: 'Phần mềm ứng dụng dùng để truy cập, duyệt xem các trang thông tin trên mạng Internet (như Chrome, Edge, Cốc Cốc).',
        explanation: 'Trình duyệt web (Web Browser) là cầu nối giúp người dùng tương tác và khai thác kho tàng tri thức khổng lồ trên mạng Internet.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 4,
      },
    ],
  },

  // GAME 2: CÔNG NGHỆ 8 - BẢN VẼ KỸ THUẬT & CƠ KHÍ
  {
    id: 'game_tech_8_catchword',
    title: 'Đuổi Hình Bắt Chữ: Bản Vẽ & Kỹ Thuật Điện 8',
    description: 'Chinh phục các câu đố hình ảnh về bản vẽ kĩ thuật, cơ khí chế tạo và thiết bị an toàn điện gia đình.',
    subjectId: 'sub_tech_8',
    subjectName: 'Công nghệ 8',
    subjectCode: 'CONG_NGHE_8',
    gameType: 'catch_word',
    schoolLevel: 'secondary',
    gradeLevel: 8,
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    totalQuestions: 4,
    playsCount: 98,
    isPublished: true,
    questions: [
      {
        id: 'q_tech8_1',
        gameId: 'game_tech_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80',
        answerText: 'BẢN VẼ KỸ THUẬT',
        hintText: 'Bản vẽ mô tả hình dạng, kích thước, vật liệu và yêu cầu kĩ thuật của một sản phẩm cơ khí.',
        explanation: 'Bản vẽ kĩ thuật là ngôn ngữ chung của ngành kĩ thuật, là căn cứ để chế tạo, kiểm tra và lắp ráp chi tiết máy.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 1,
      },
      {
        id: 'q_tech8_2',
        gameId: 'game_tech_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
        answerText: 'AN TOÀN ĐIỆN',
        hintText: 'Các quy tắc và thiết bị như Aptomat, cầu chì nhằm bảo vệ tính mạng con người khi dùng điện.',
        explanation: 'An toàn điện là tập hợp các biện pháp phòng ngừa tai nạn điện giật, cháy nổ điện trong sinh hoạt và sản xuất.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 2,
      },
      {
        id: 'q_tech8_3',
        gameId: 'game_tech_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
        answerText: 'TIẾT KIỆM NĂNG LƯỢNG',
        hintText: 'Hành động tắt thiết bị điện khi không sử dụng và tận dụng ánh sáng tự nhiên.',
        explanation: 'Sử dụng năng lượng tiết kiệm và hiệu quả góp phần giảm chi phí sinh hoạt và bảo vệ môi trường sinh thái.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 3,
      },
      {
        id: 'q_tech8_4',
        gameId: 'game_tech_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&auto=format&fit=crop&q=80',
        answerText: 'TRUYỀN CHUYỂN ĐỘNG',
        hintText: 'Cơ cấu bánh răng, xích líp truyền chuyển động quay từ trục này sang trục khác trong máy cơ khí.',
        explanation: 'Cơ cấu truyền và biến đổi chuyển động giúp truyền lực và biến đổi tốc độ theo yêu cầu công việc.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 4,
      },
    ],
  },

  // GAME 3: HOẠT ĐỘNG TRẢI NGHIỆM, HƯỚNG NGHIỆP 9 - BẢN THÂN VÀ TƯƠNG LAI
  {
    id: 'game_hdtn_9_catchword',
    title: 'Đuổi Hình Bắt Chữ: Định Hướng Tương Lai 9',
    description: 'Khám phá thế giới nghề nghiệp, kỹ năng mềm và con đường chọn trường THPT phù hợp với năng lực bản thân.',
    subjectId: 'sub_hdtn_9',
    subjectName: 'HĐTN, hướng nghiệp 9',
    subjectCode: 'HDTN_HN_9',
    gameType: 'catch_word',
    schoolLevel: 'secondary',
    gradeLevel: 9,
    thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&auto=format&fit=crop&q=80',
    totalQuestions: 4,
    playsCount: 165,
    isPublished: true,
    questions: [
      {
        id: 'q_hdtn9_1',
        gameId: 'game_hdtn_9_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
        answerText: 'KỸ NĂNG GIAO TIẾP',
        hintText: 'Khả năng lắng nghe, thấu cảm và truyền đạt ý kiến một cách lịch sự, thuyết phục.',
        explanation: 'Kỹ năng giao tiếp là một trong những kĩ năng thế kỉ 21 cốt lõi giúp học sinh tự tin hòa nhập và thành công trong mọi lĩnh vực nghề nghiệp.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 1,
      },
      {
        id: 'q_hdtn9_2',
        gameId: 'game_hdtn_9_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80',
        answerText: 'LẬP KẾ HOẠCH HỌC TẬP',
        hintText: 'Việc sắp xếp thời gian biểu, mục tiêu điểm số và các bước ôn thi vào lớp 10 rõ ràng.',
        explanation: 'Lập kế hoạch học tập giúp rèn luyện thói quen tự chủ, quản lý thời gian hiệu quả và giảm bớt áp lực thi cử.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 2,
      },
      {
        id: 'q_hdtn9_3',
        gameId: 'game_hdtn_9_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
        answerText: 'ĐỊNH HƯỚNG NGHỀ NGHIỆP',
        hintText: 'Quá trình tìm hiểu sở thích, năng lực cá nhân và nhu cầu xã hội để chọn ngành nghề tương lai.',
        explanation: 'Định hướng nghề nghiệp đúng từ cấp THCS giúp học sinh có động lực học tập và chọn đúng tổ hợp môn khi bước vào cấp THPT.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 3,
      },
      {
        id: 'q_hdtn9_4',
        gameId: 'game_hdtn_9_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&auto=format&fit=crop&q=80',
        answerText: 'TINH THẦN ĐỒNG ĐỘI',
        hintText: 'Sự gắn kết, hỗ trợ lẫn nhau giữa các thành viên trong nhóm để cùng hoàn thành mục tiêu chung.',
        explanation: 'Tinh thần đồng đội (Teamwork) giúp nhân đôi sức mạnh, xây dựng mối quan hệ gắn bó bền chặt và tạo ra những kết quả vượt bậc.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 4,
      },
    ],
  },

  // GAME 4: TIN HỌC 8 - THUẬT TOÁN VÀ LẬP TRÌNH
  {
    id: 'game_it_8_catchword',
    title: 'Đuổi Hình Bắt Chữ: Tư Duy Thuật Toán & Lập Trình 8',
    description: 'Chinh phục các câu đố trực quan về vòng lặp, biến nhớ, điều kiện rẽ nhánh và thuật toán máy tính.',
    subjectId: 'sub_it_8',
    subjectName: 'Tin học 8',
    subjectCode: 'TIN_HOC_8',
    gameType: 'catch_word',
    schoolLevel: 'secondary',
    gradeLevel: 8,
    thumbnailUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    totalQuestions: 3,
    playsCount: 88,
    isPublished: true,
    questions: [
      {
        id: 'q_it8_1',
        gameId: 'game_it_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1516116211227-bbc1b08f4388?w=800&auto=format&fit=crop&q=80',
        answerText: 'THUẬT TOÁN TÌM KIẾM',
        hintText: 'Dãy các chỉ dẫn từng bước để tìm ra vị trí của một phần tử dữ liệu trong danh sách.',
        explanation: 'Thuật toán tìm kiếm tuần tự và tìm kiếm nhị phân là nền tảng quan trọng giúp máy tính xử lý và tra cứu dữ liệu cực nhanh.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 1,
      },
      {
        id: 'q_it8_2',
        gameId: 'game_it_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&auto=format&fit=crop&q=80',
        answerText: 'CẤU TRÚC LẶP',
        hintText: 'Khối lệnh được thực hiện lặp đi lặp lại nhiều lần cho đến khi thỏa mãn một điều kiện dừng.',
        explanation: 'Cấu trúc lặp (Loop) giúp tự động hóa các thao tác lặp lại trong chương trình máy tính, tối ưu hóa thời gian và dòng mã nguồn.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 2,
      },
      {
        id: 'q_it8_3',
        gameId: 'game_it_8_catchword',
        imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
        answerText: 'LẬP TRÌNH TRỰC QUAN',
        hintText: 'Phương pháp kéo thả các khối lệnh nhiều màu sắc để tạo trò chơi hoặc câu chuyện tương tác.',
        explanation: 'Lập trình trực quan (như Scratch) giúp học sinh làm quen với tư duy máy tính một cách hào hứng, trực quan mà không bị bỡ ngỡ về cú pháp.',
        timeLimitSeconds: 45,
        points: 100,
        orderIndex: 3,
      },
    ],
  },
];
